<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_01_PLCTASK" Id="{2bfdc5e4-1ee6-0d1d-0a20-6205358c4b9f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_01_PLCTASK
VAR
     fbLogHandler: FB_LogHandler;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//PRG_AL1K3_L2SI();
PRG_SL1K3_SCATTER();
//PRG_AT1K3_SOLID();
PRG_PMPS();
fbLogHandler();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>